var vm = new Vue({
    el: "#app",
    data: {
        tag_list: [{tag: "机器学习", url: "./images/ml_icon.png"}, 
                    {tag: "数据库", url: "./images/db_icon.png"}, 
                    {tag: "javascript", url: "./images/js_icon.png"}, 
                    {tag: "Vue.js", url:"./images/vue_icon.png"},
                    {tag: "Django", url:"./images/django_icon.png"}],
        statistics: {view_num: 0, article_num: 0, comment_num: 0},
        article_list: [{image_url: "./images/article_img.png", title: "Javascript继承",
                        intro: "继承是面向对象编程语言的一个特性，子类继承父类的特征和行为，使得子类对象（实例）具有父类的实例域和方法，或子类从父类继承...",
                         time: "2019-9-8"}, {image_url: "./images/article_img.png", title: "Javascript继承",
                         intro: "继承是面向对象编程语言的一个特性，子类继承父类的特征和行为，使得子类对象（实例）具有父类的实例域和方法，或子类从父类继承...",
                          time: "2019-9-8"}, {image_url: "./images/article_img.png", title: "Javascript继承",
                          intro: "继承是面向对象编程语言的一个特性，子类继承父类的特征和行为，使得子类对象（实例）具有父类的实例域和方法，或子类从父类继承...",
                           time: "2019-9-8"}, {image_url: "./images/article_img.png", title: "Javascript继承",
                           intro: "继承是面向对象编程语言的一个特性，子类继承父类的特征和行为，使得子类对象（实例）具有父类的实例域和方法，或子类从父类继承...",
                            time: "2019-9-8"}, {image_url: "./images/article_img.png", title: "Javascript继承",
                            intro: "继承是面向对象编程语言的一个特性，子类继承父类的特征和行为，使得子类对象（实例）具有父类的实例域和方法，或子类从父类继承...",
                             time: "2019-9-8"}, {image_url: "./images/article_img.png", title: "Javascript继承",
                             intro: "继承是面向对象编程语言的一个特性，子类继承父类的特征和行为，使得子类对象（实例）具有父类的实例域和方法，或子类从父类继承...",
                              time: "2019-9-8"}, {image_url: "./images/article_img.png", title: "Javascript继承",
                              intro: "继承是面向对象编程语言的一个特性，子类继承父类的特征和行为，使得子类对象（实例）具有父类的实例域和方法，或子类从父类继承...",
                               time: "2019-9-8"}, {image_url: "./images/article_img.png", title: "Javascript继承",
                               intro: "继承是面向对象编程语言的一个特性，子类继承父类的特征和行为，使得子类对象（实例）具有父类的实例域和方法，或子类从父类继承...",
                                time: "2019-9-8"}, {image_url: "./images/article_img.png", title: "Javascript继承",
                                intro: "继承是面向对象编程语言的一个特性，子类继承父类的特征和行为，使得子类对象（实例）具有父类的实例域和方法，或子类从父类继承...",
                                 time: "2019-9-8"}, {image_url: "./images/article_img.png", title: "Javascript继承",
                                 intro: "继承是面向对象编程语言的一个特性，子类继承父类的特征和行为，使得子类对象（实例）具有父类的实例域和方法，或子类从父类继承...",
                                  time: "2019-9-8"}, {image_url: "./images/article_img.png", title: "Javascript继承",
                                  intro: "继承是面向对象编程语言的一个特性，子类继承父类的特征和行为，使得子类对象（实例）具有父类的实例域和方法，或子类从父类继承...",
                                   time: "2019-9-8"}, {image_url: "./images/article_img.png", title: "Javascript继承",
                                   intro: "继承是面向对象编程语言的一个特性，子类继承父类的特征和行为，使得子类对象（实例）具有父类的实例域和方法，或子类从父类继承...",
                                    time: "2019-9-8"}],
    },
    methods: {
        
    },
})